//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroArmas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMA
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string CATEGORIA { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<int> PRECIO { get; set; }
        public Nullable<int> ANIO_CREACION { get; set; }
        public string FECHA_VENTA { get; set; }
    }
}
